{{- if ne .Release.IsInstall true -}}
{{- if .Values.migrateJob.enable }}
apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-sites-{{ template "erpnext.fullname" . }}-{{ date "20060102150405" .Release.Now }}
spec:
  backoffLimit: 1
  template:
    spec:
      serviceAccountName: {{ template "erpnext.serviceAccountName" $ }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      initContainers:
      - name: set-maintenance-mode
        image: stedolan/jq
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash", "-c"]
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        args:
          - cp /data/common_site_config.json /data/temp.json;
            jq -r '.maintenance_mode=1 | .pause_scheduler=1' /data/temp.json > /data/common_site_config.json;
        volumeMounts:
          - name: sites-dir
            mountPath: "/data"
      - name: populate-assets
        image: "{{ .Values.nginxImage.repository }}:{{ .Values.nginxImage.tag }}"
        command: ["/bin/bash", "-c"]
        args:
          - "rsync -a --delete /var/www/html/assets/frappe /assets"
        volumeMounts:
          - name: assets-cache
            mountPath: /assets
      {{- if .Values.migrateJob.backup }}
      - name: backup
        image: "{{ .Values.pythonImage.repository }}:{{ .Values.pythonImage.tag }}"
        args: ["backup"]
        imagePullPolicy: {{ .Values.pythonImage.pullPolicy }}
        securityContext:
          {{- toYaml $.Values.securityContext | nindent 12 }}
        volumeMounts:
          - name: sites-dir
            mountPath: /home/frappe/frappe-bench/sites
      {{- end }}
      containers:
      - name: migrate
        image: "{{ .Values.pythonImage.repository }}:{{ .Values.pythonImage.tag }}"
        # args: ["migrate"]
        # terminate istio when done
        command:
          - /bin/sh
          - -c
          - |
            until curl -fsI http://localhost:15021/healthz/ready; do echo \"Waiting for Sidecar...\"; sleep 3; done;
            echo \"Sidecar available. Running the command...\";
            /usr/local/bin/docker-entrypoint.sh migrate;
            x=$(echo $?); curl -fsI -X POST http://localhost:15020/quitquitquit && exit $x
        securityContext:
          {{- toYaml $.Values.securityContext | nindent 12 }}
        env:
          - name: "MAINTENANCE_MODE"
            value: "1"
        imagePullPolicy: {{ .Values.pythonImage.pullPolicy }}
        volumeMounts:
          - name: sites-dir
            mountPath: /home/frappe/frappe-bench/sites
          - name: assets-cache
            mountPath: /home/frappe/frappe-bench/sites/assets
      restartPolicy: Never
      volumes:
        - name: assets-cache
          emptyDir: {}
        - name: sites-dir
          {{- if .Values.persistence.worker.enabled }}
          persistentVolumeClaim:
            {{- if .Values.persistence.worker.existingClaim }}
            claimName: {{ .Values.persistence.worker.existingClaim }}
            {{- else }}
            claimName: {{ template "erpnext.fullname" . }}
            {{- end }}
            readOnly: false
          {{- else }}
          emptyDir: {}
          {{- end }}
{{- end }}
{{- end }}
