{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "erpnext.serviceAccountName" . }}
  labels:
    {{- include "erpnext.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "erpnext.serviceAccountName" . }}-redis
  labels:
    {{- include "erpnext.labels" . | nindent 4 }}
    app.kubernetes.io/name: erpnext-redis
{{- end }}