language: python
os: linux
dist: xenial

services:
  - docker

python:
  - '3.6'
env:
  - GIT_SSH_COMMAND="ssh -i ${PWD}/deploy_key"

before_install:
  - if [[ "$TRAVIS_PULL_REQUEST" = "false" ]]; then
      openssl aes-256-cbc -K $encrypted_189e52c2c347_key -iv $encrypted_189e52c2c347_iv -in deploy_key.enc -out deploy_key -d;
      chmod 400 deploy_key;
    fi
install:
  - curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
script:
  - helm lint erpnext
  - pip install chartpress
deploy:
  - provider: script
    skip_cleanup: true
    script: chartpress --publish-chart
    on:
      branch: master
      tags: true
jobs:
  include:
    - stage: "Test Install and Upgrade of Frappe/ERPNext Helm Chart"
      if: type = pull_request
      before_install:
        - sudo apt-get update && sudo apt-get install -y apt-transport-https ca-certificates curl
        - sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
        - echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
        - sudo apt-get update && sudo apt-get install -y kubectl
        - curl -s https://raw.githubusercontent.com/rancher/k3d/main/install.sh | bash
      script:
        - ./tests/script.sh
